add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$jobs\
$line_break\
$character\
"""

[directory]
truncation_length = 3
truncate_to_repo = false
style = "cyan"
repo_root_style = "purple"
truncation_symbol = "..."
read_only = " "
read_only_style = "red"

[git_branch]
style = "purple"
symbol = " "
format = "$symbol[$branch(:$remotebranch)]($style)"

[git_status]
style = "purple"
modified = "${count}"
format = "[(\\($modified\\)) ]($style)"

[cmd_duration]
style = "yellow dimmed"
format = "[$duration]($style) "

[jobs]
style = "red bold"
symbol = "●"
format = "[$symbol]($style)"
