add_newline = true

format = """
$directory\
$hostname\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$username\
$character\
$python
"""

[directory]
truncation_length = 3
truncate_to_repo = false
style = "cyan"
repo_root_style = "purple"
truncation_symbol = ""
read_only = " "
read_only_style = "red"

[git_branch]
style = "purple"
symbol = " "
format = "$symbol[$branch(:$remotebranch) ]($style)"

[git_status]
style = "purple"
modified = "${count}"
format = "[(\\[$modified\\]) ]($style)"

[cmd_duration]
style = "yellow dimmed"
format = "[$duration]($style)"

[username]
style_root = "red"
style_user = "yellow"
format = "[$user]($style) "

[hostname]
format = "on [$hostname]($style) "

[python]
style = "yellow bold"
format = "[${virtualenv}]($style) "
