add_newline = true

format = """
$directory\
$hostname\
$git_branch\
$git_status\
${custom.colima}\
$cmd_duration\
$line_break\
$username\
$character
"""

[directory]
truncation_length = 3
truncate_to_repo = false
style = "cyan"
repo_root_style = "purple"
truncation_symbol = ""
read_only = " "
read_only_style = "red"

[git_branch]
style = "purple"
symbol = " "
format = "$symbol[$branch(:$remotebranch) ]($style)"

[git_status]
style = "purple"
modified = "${count}"
format = "[(\\[$modified\\]) ]($style)"

[cmd_duration]
style = "yellow dimmed"
format = "[$duration]($style)"

[custom.colima]
symbol = " "
style = "blue"
when = "echo $COLIMA_STATE | grep ."
command = "echo $COLIMA_STATE"
format = "[$symbol($output) ]($style)"

[username]
style_root = "red"
style_user = "yellow"
format = "[$user]($style) "

[hostname]
format = "on [$hostname]($style) "
