theme = "catppuccin_macchiato"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
g = { x = ":buffer-close"}
J = ["delete_selection", "paste_after"]
K = ["delete_selection", "move_line_up", "paste_before"]

[keys.normal.space]
y = ":clipboard-yank"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
R = ":clipboard-paste-replace"

[editor]
line-number = "relative"
cursorline = true
bufferline = "always"
shell = ["zsh", "-c"]
scrolloff = 10
color-modes = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
right = ["file-modification-indicator", "spacer", "diagnostics", "spacer","position-percentage", "spacer"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true

[editor.indent-guides]
render = true

