theme = "tokyonight_storm"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
J = ["delete_selection", "paste_after"]
K = ["delete_selection", "move_line_up", "paste_before"]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]

[keys.normal.g]
x = ":buffer-close"
j = "jump_backward"
k = "jump_forward"

[keys.normal.backspace]
b = ":run-shell-command zellij run -f -- make build"
r = ":run-shell-command zellij run -f -- make run"
g = ":run-shell-command zellij run -fc -- lazygit"
f = ":run-shell-command zellij run -fc -- mc"

[editor]
line-number = "relative"  
cursorline = true
bufferline = "always"
shell = ["zsh", "-c"]
scrolloff = 10
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
completion-trigger-len = 1

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer","diagnostics","spinner"]
right = ["file-modification-indicator", "spacer", "file-type", "spacer","position-percentage", "spacer"]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true

[editor.indent-guides]
render = true

