theme = "tokyonight_storm"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
J = ["delete_selection", "paste_after"]
K = ["delete_selection", "move_line_up", "paste_before"]
C-x = ":buffer-close"
"\\" = "buffer_picker"
"tab" = "goto_next_paragraph"
"S-tab" = "goto_prev_paragraph"
a = ["move_char_right", "insert_mode"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal.backspace]
b = ":run-shell-command zellij run -f -- just build"
r = ":run-shell-command zellij run -f -- just run"
t = ":run-shell-command zellij run -f -- just test"
g = ":run-shell-command zellij run -fc -- lazygit"
f = ":run-shell-command zellij run -fc -- broot"
e = [":config-reload", ":reload-all", ":lsp-restart"]

[editor]
true-color = true
line-number = "relative"
cursorline = true
bufferline = "never"
scrolloff = 10
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
completion-trigger-len = 1
shell = ["sh", "-c"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name", "diagnostics", "workspace-diagnostics", "spinner"]
right = [
  "read-only-indicator",
  "file-modification-indicator",
  "file-type",
  "position-percentage",
  "total-line-numbers",
]

[editor.lsp]
auto-signature-help = true
display-messages = true

[editor.indent-guides]
render = true

[editor.smart-tab]
supersede-menu = true
