[[language]]
name = "python"
roots = [".python-version", "pyrightconfig.json", "main.py", ".git", "pyproject.toml", "Pipfile"]
language-server = { command = "pyright-langserver", args = ["--stdio"]}
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
config = { }
