# python
[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[langauge-server.ruff.config.settings]
args = ["--ignore", "E501"]

# bash
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true

# rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'"' = '"'
"'" = "'"
'`' = '`'
'[' = ']'
'<' = '>'

# typescript
[[language]]
name = "typescript"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "typescript"]

# toml
[[language]]
name = "toml"
auto-format = true

# yaml
[[language]]
name = "yaml"
auto-format = true

# dockerfile
[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true

# html
[[language]]
name = "html"
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'"' = '"'
"'" = "'"
'`' = '`'
'[' = ']'
'<' = '>'

#gotmpl

[[language]]
name = "gotmpl"
language-servers = ["gopls", "vscode-html-language-server"]
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'"' = '"'
"'" = "'"
'`' = '`'
'[' = ']'
'<' = '>'
